---

  - hosts: ws
    remote_user: root
    tasks: 
      - name: Install nginx
        apt:
          name: nginx
          update_cache: true
          allow_unauthenticated: true
      - name: Install index.html
        template:
          src: files/index.html
          dest: /var/www/html